### ISSUE TITLE
Release 0.12.1 doesn't work on ARM64

### ISSUE THREAD

**Issue by Jojonintendo** [LemmyNet/lemmy#1771]
Latest release doesn't work on ARM64, even the tag 0.12.2-rc.1. Previous version works fine.

### Steps to Reproduce

1. Install Lemmy via docker following the official guide [here](https://join-lemmy.org/docs/en/administration/install_docker.html).
2. The lemmy_lemmy-ui_1 container shows the following error repeatedly:
```
thread 'main' panicked at 'Failed to load settings file: LemmyError { inner: No such file or directory (os error 2) }', crates/utils/src/settings/mod.rs:12:34
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
3. I was advised that despite it being the ui container, this was Lemmy failing to find `lemmy.hjson`. The file is there however.

### Technical details

* Please post your log: `sudo docker-compose logs > lemmy_log.out`:
```
Attaching to lemmy_lemmy-ui_1, lemmy_lemmy_1, lemmy_postgres_1, lemmy_pictrs_1
[36mlemmy-ui_1  |[0m thread 'main' panicked at 'Failed to load settings file: LemmyError { inner: No such file or directory (os error 2) }', crates/utils/src/settings/mod.rs:12:34
[36mlemmy-ui_1  |[0m note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[36mlemmy-ui_1  |[0m thread 'main' panicked at 'Failed to load settings file: LemmyError { inner: No such file or directory (os error 2) }', crates/utils/src/settings/mod.rs:12:34
[36mlemmy-ui_1  |[0m note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[36mlemmy-ui_1  |[0m thread 'main' panicked at 'Failed to load settings file: LemmyError { inner: No such file or directory (os error 2) }', crates/utils/src/settings/mod.rs:12:34
[36mlemmy-ui_1  |[0m note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[36mlemmy-ui_1  |[0m thread 'main' panicked at 'Failed to load settings file: LemmyError { inner: No such file or directory (os error 2) }', crates/utils/src/settings/mod.rs:12:34
[36mlemmy-ui_1  |[0m note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[36mlemmy-ui_1  |[0m thread 'main' panicked at 'Failed to load settings file: LemmyError { inner: No such file or directory (os error 2) }', crates/utils/src/settings/mod.rs:12:34
[36mlemmy-ui_1  |[0m note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[36mlemmy-ui_1  |[0m thread 'main' panicked at 'Failed to load settings file: LemmyError { inner: No such file or directory (os error 2) }', crates/utils/src/settings/mod.rs:12:34
[36mlemmy-ui_1  |[0m note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[36mlemmy-ui_1  |[0m thread 'main' panicked at 'Failed to load settings file: LemmyError { inner: No such file or directory (os error 2) }', crates/utils/src/settings/mod.rs:12:34
[36mlemmy-ui_1  |[0m note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[36mlemmy-ui_1  |[0m thread 'main' panicked at 'Failed to load settings file: LemmyError { inner: No such file or directory (os error 2) }', crates/utils/src/settings/mod.rs:12:34
[36mlemmy-ui_1  |[0m note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[36mlemmy-ui_1  |[0m thread 'main' panicked at 'Failed to load settings file: LemmyError { inner: No such file or directory (os error 2) }', crates/utils/src/settings/mod.rs:12:34
[36mlemmy-ui_1  |[0m note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[36mlemmy-ui_1  |[0m thread 'main' panicked at 'Failed to load settings file: LemmyError { inner: No such file or directory (os error 2) }', crates/utils/src/settings/mod.rs:12:34
[36mlemmy-ui_1  |[0m note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[36mlemmy-ui_1  |[0m thread 'main' panicked at 'Failed to load settings file: LemmyError { inner: No such file or directory (os error 2) }', crates/utils/src/settings/mod.rs:12:34
[36mlemmy-ui_1  |[0m note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[36mlemmy-ui_1  |[0m thread 'main' panicked at 'Failed to load settings file: LemmyError { inner: No such file or directory (os error 2) }', crates/utils/src/settings/mod.rs:12:34
[36mlemmy-ui_1  |[0m note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[36mlemmy-ui_1  |[0m thread 'main' panicked at 'Failed to load settings file: LemmyError { inner: No such file or directory (os error 2) }', crates/utils/src/settings/mod.rs:12:34
[36mlemmy-ui_1  |[0m note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[36mlemmy-ui_1  |[0m thread 'main' panicked at 'Failed to load settings file: LemmyError { inner: No such file or directory (os error 2) }', crates/utils/src/settings/mod.rs:12:34
[36mlemmy-ui_1  |[0m note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[36mlemmy-ui_1  |[0m thread 'main' panicked at 'Failed to load settings file: LemmyError { inner: No such file or directory (os error 2) }', crates/utils/src/settings/mod.rs:12:34
[36mlemmy-ui_1  |[0m note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[33mlemmy_1     |[0m warning: invalid logging spec 'info"', ignoring it
[33mlemmy_1     |[0m [2021-09-06T13:01:57Z INFO  lemmy_server::code_migrations] Running user_updates_2020_04_02
[33mlemmy_1     |[0m [2021-09-06T13:01:57Z INFO  lemmy_server::code_migrations] 0 person rows updated.
[33mlemmy_1     |[0m [2021-09-06T13:01:57Z INFO  lemmy_server::code_migrations] Running community_updates_2020_04_02
[33mlemmy_1     |[0m [2021-09-06T13:01:57Z INFO  lemmy_server::code_migrations] 0 community rows updated.
[33mlemmy_1     |[0m [2021-09-06T13:01:57Z INFO  lemmy_server::code_migrations] Running post_updates_2020_04_03
[33mlemmy_1     |[0m [2021-09-06T13:01:57Z INFO  lemmy_server::code_migrations] 0 post rows updated.
[33mlemmy_1     |[0m [2021-09-06T13:01:57Z INFO  lemmy_server::code_migrations] Running comment_updates_2020_04_03
[33mlemmy_1     |[0m [2021-09-06T13:01:57Z INFO  lemmy_server::code_migrations] 0 comment rows updated.
[33mlemmy_1     |[0m [2021-09-06T13:01:57Z INFO  lemmy_server::code_migrations] Running private_message_updates_2020_05_05
[33mlemmy_1     |[0m [2021-09-06T13:01:57Z INFO  lemmy_server::code_migrations] 0 private message rows updated.
[33mlemmy_1     |[0m [2021-09-06T13:01:57Z INFO  lemmy_server::code_migrations] Running post_thumbnail_url_updates_2020_07_27
[33mlemmy_1     |[0m [2021-09-06T13:01:57Z INFO  lemmy_server::code_migrations] 0 Post thumbnail_url rows updated.
[33mlemmy_1     |[0m [2021-09-06T13:01:57Z INFO  lemmy_server::code_migrations] Running apub_columns_2021_02_02
[33mlemmy_1     |[0m [2021-09-06T13:01:57Z INFO  lemmy_server::scheduled_tasks] Updating active site and community aggregates ...
[33mlemmy_1     |[0m Starting http server at 0.0.0.0:8536
[32mpictrs_1    |[0m [2mSep 06 13:01:55.438[0m [32m INFO[0m actix_server::builder: Starting 4 workers    
[32mpictrs_1    |[0m [2mSep 06 13:01:55.440[0m [32m INFO[0m actix_server::builder: Starting "actix-web-service-0.0.0.0:8080" service on 0.0.0.0:8080    
[33mlemmy_1     |[0m [2021-09-06T13:01:57Z INFO  lemmy_server::scheduled_tasks] Done.
[33mlemmy_1     |[0m [2021-09-06T13:01:57Z INFO  lemmy_server::scheduled_tasks] Reindexing table  post_aggregates ...
[33mlemmy_1     |[0m [2021-09-06T13:01:57Z INFO  lemmy_server::scheduled_tasks] Done.
[33mlemmy_1     |[0m [2021-09-06T13:01:57Z INFO  lemmy_server::scheduled_tasks] Reindexing table  comment_aggregates ...
[33mlemmy_1     |[0m [2021-09-06T13:01:57Z INFO  lemmy_server::scheduled_tasks] Done.
[33mlemmy_1     |[0m [2021-09-06T13:01:57Z INFO  lemmy_server::scheduled_tasks] Reindexing table  community_aggregates ...
[33mlemmy_1     |[0m [2021-09-06T13:01:57Z INFO  lemmy_server::scheduled_tasks] Done.
[33mlemmy_1     |[0m [2021-09-06T13:01:57Z INFO  lemmy_server::scheduled_tasks] Clearing old activities...
[33mlemmy_1     |[0m [2021-09-06T13:01:57Z INFO  lemmy_server::scheduled_tasks] Done.
[33mlemmy_1     |[0m [2021-09-06T14:00:00Z INFO  lemmy_server::scheduled_tasks] Updating active site and community aggregates ...
[33mlemmy_1     |[0m [2021-09-06T14:00:00Z INFO  lemmy_server::scheduled_tasks] Done.
[33mlemmy_1     |[0m [2021-09-06T14:00:00Z INFO  lemmy_server::scheduled_tasks] Reindexing table concurrently post_aggregates ...
[33mlemmy_1     |[0m [2021-09-06T14:00:00Z INFO  lemmy_server::scheduled_tasks] Done.
[33mlemmy_1     |[0m [2021-09-06T14:00:00Z INFO  lemmy_server::scheduled_tasks] Reindexing table concurrently comment_aggregates ...
[33mlemmy_1     |[0m [2021-09-06T14:00:00Z INFO  lemmy_server::scheduled_tasks] Done.
[33mlemmy_1     |[0m [2021-09-06T14:00:00Z INFO  lemmy_server::scheduled_tasks] Reindexing table concurrently community_aggregates ...
[33mlemmy_1     |[0m [2021-09-06T14:00:01Z INFO  lemmy_server::scheduled_tasks] Done.
[33mlemmy_1     |[0m [2021-09-06T15:00:00Z INFO  lemmy_server::scheduled_tasks] Updating active site and community aggregates ...
[33mlemmy_1     |[0m [2021-09-06T15:00:00Z INFO  lemmy_server::scheduled_tasks] Done.
[33mlemmy_1     |[0m [2021-09-06T15:00:00Z INFO  lemmy_server::scheduled_tasks] Reindexing table concurrently post_aggregates ...
[33mlemmy_1     |[0m [2021-09-06T15:00:01Z INFO  lemmy_server::scheduled_tasks] Done.
[33mlemmy_1     |[0m [2021-09-06T15:00:01Z INFO  lemmy_server::scheduled_tasks] Reindexing table concurrently comment_aggregates ...
[33mlemmy_1     |[0m [2021-09-06T15:00:01Z INFO  lemmy_server::scheduled_tasks] Done.
[33mlemmy_1     |[0m [2021-09-06T15:00:01Z INFO  lemmy_server::scheduled_tasks] Reindexing table concurrently community_aggregates ...
[33mlemmy_1     |[0m [2021-09-06T15:00:01Z INFO  lemmy_server::scheduled_tasks] Done.
[33mlemmy_1     |[0m [2021-09-06T16:00:00Z INFO  lemmy_server::scheduled_tasks] Updating active site and community aggregates ...
[33mlemmy_1     |[0m [2021-09-06T16:00:00Z INFO  lemmy_server::scheduled_tasks] Done.
[33mlemmy_1     |[0m [2021-09-06T16:00:00Z INFO  lemmy_server::scheduled_tasks] Reindexing table concurrently post_aggregates ...
[33mlemmy_1     |[0m [2021-09-06T16:00:00Z INFO  lemmy_server::scheduled_tasks] Done.
[33mlemmy_1     |[0m [2021-09-06T16:00:00Z INFO  lemmy_server::scheduled_tasks] Reindexing table concurrently comment_aggregates ...
[33mlemmy_1     |[0m [2021-09-06T16:00:00Z INFO  lemmy_server::scheduled_tasks] Done.
[33mlemmy_1     |[0m [2021-09-06T16:00:00Z INFO  lemmy_server::scheduled_tasks] Reindexing table concurrently community_aggregates ...
[33mlemmy_1     |[0m [2021-09-06T16:00:00Z INFO  lemmy_server::scheduled_tasks] Done.
[35mpostgres_1  |[0m 
[35mpostgres_1  |[0m PostgreSQL Database directory appears to contain a database; Skipping initialization
[35mpostgres_1  |[0m 
[35mpostgres_1  |[0m 2021-09-06 13:01:51.889 UTC [1] LOG:  starting PostgreSQL 12.8 on aarch64-unknown-linux-musl, compiled by gcc (Alpine 10.3.1_git20210424) 10.3.1 20210424, 64-bit
[35mpostgres_1  |[0m 2021-09-06 13:01:51.890 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
[35mpostgres_1  |[0m 2021-09-06 13:01:51.890 UTC [1] LOG:  listening on IPv6 address "::", port 5432
[35mpostgres_1  |[0m 2021-09-06 13:01:51.898 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
[35mpostgres_1  |[0m 2021-09-06 13:01:51.950 UTC [21] LOG:  database system was shut down at 2021-09-06 13:01:29 UTC
[35mpostgres_1  |[0m 2021-09-06 13:01:51.980 UTC [1] LOG:  database system is ready to accept connections
```
* What OS are you trying to install lemmy on?
openSUSE TumbleWeed on ROCK64, AARCH64 SBC.
* Any browser console errors?
No, the page gives a 502 error.

**Comment by dessalines** [comment]
Post your `docker-compose.yml`, and `lemmy.hjson` files.

Also I just updated to `0.12.2`, and ARM builds should work fine there.

**Comment by Jojonintendo** [comment]
Sure, these are the files.

docker-compose.yml:
```
version: '2.2'

services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=lemmy
      - POSTGRES_PASSWORD=*****
      - POSTGRES_DB=lemmy
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    restart: always

  lemmy:
#    image: dessalines/lemmy:0.11.3
    image: dessalines/lemmy:0.12.2
    ports:
      - "127.0.0.1:8536:8536"
    restart: always
    environment:
      - RUST_LOG="warn,lemmy_server=info,lemmy_api=info,lemmy_api_common=info,lemmy_api_crud=info,lemmy_apub=info,lemmy_db_queries=info,lemmy_db_schema=info,lemmy_db_views=info,lemmy_db_views_actor=info,lemmy_db_views_moderator=info,lemmy_routes=info,lemmy_utils=info,lemmy_websocket=info"
    volumes:
      - ./lemmy.hjson:/config/config.hjson
    depends_on:
      - postgres
      - pictrs

  lemmy-ui:
#    image: dessalines/lemmy-ui:0.11.3
    image: dessalines/lemmy:0.12.2
    ports:
      - "127.0.0.1:1235:1234"
    restart: always
    environment:
      - LEMMY_INTERNAL_HOST=lemmy:8536
      - LEMMY_EXTERNAL_HOST=lemmy.jdelcampo.eu
      - LEMMY_HTTPS=true
    depends_on: 
      - lemmy

  pictrs:
    image: asonix/pictrs:v0.2.6-r2
    ports: 
      - "127.0.0.1:8537:8080"
    user: 991:991
    volumes:
      - ./volumes/pictrs:/mnt
    restart: always
```
lemmy.hjson:
```
{
  # for more info about the config, check out the documentation
  # https://join-lemmy.org/docs/en/administration/configuration.html

  setup: {
    # username for the admin user
    admin_username: "*****"
    # password for the admin user
    admin_password: "*****"
    # name of the site (can be changed later)
    site_name: "Lemmy"
  }

  # the domain name of your instance (eg "lemmy.ml")
  hostname: "lemmy.jdelcampo.eu"
  # address where lemmy should listen for incoming requests
  bind: "0.0.0.0"
  # port where lemmy should listen for incoming requests
  port: 8536
  # json web token for authorization between server and client
  jwt_secret: "*****"
  # settings related to the postgresql database
  database: {
    # name of the postgres database for lemmy
    database: "lemmy"
    # username to connect to postgres
    user: "lemmy"
    # password to connect to postgres
    password: "*****"
    # host where postgres is running
    host: "postgres"
    # port where postgres can be accessed
    port: 5432
    # maximum number of active sql connections
    pool_size: 5
  }
#  # optional: email sending configuration
#  email: {
#    # hostname and port of the smtp server
#    smtp_server: ""
#    # login name for smtp server
#    smtp_login: ""
#    # password to login to the smtp server
#    smtp_password: ""
#    # address to send emails from, eg "noreply@your-instance.com"
#    smtp_from_address: ""
#    # whether or not smtp connections should use tls
#    use_tls: true
#  }
  federation: {
    enabled: true
    tls_enabled: true
    # allowed_instances: lemmy.ml,other_instance.tld,... uncomment this to use an allowlist
  }
}
```
Also, as you can see from the docker-compose.yml file, this is with the 0.12.2 version, but the same problem persists.

**Comment by dessalines** [comment]
lemmy-ui:
#    image: dessalines/lemmy-ui:0.11.3
    image: dessalines/lemmy:0.12.2

You need to use lemmy-ui:0.12.2 there.

**Comment by Jojonintendo** [comment]
That explains why this container would show logs of a different image. Many thanks for noticing!
