### ISSUE TITLE
Lemmy fails to run with local dev setup, DatabaseError

### ISSUE THREAD

**Issue by prezmix** [LemmyNet/lemmy#1846]
### Issue Summary

Lemmy backend fails to run `Reindexing table concurrently post_aggregates` using latest source. 

### Steps to Reproduce

Followed local dev instructionson https://join-lemmy.org/docs/en/contributing/local_development.html on Debian distro.

### Technical details

```
root@5f16f5299b4e:/data/lemmy# RUST_BACKTRACE=1 cargo run
    Finished dev [unoptimized] target(s) in 1.02s
     Running `target/debug/lemmy_server`
warning: invalid logging spec 'info"', ignoring it
[2021-10-15T07:08:41Z INFO  lemmy_server::code_migrations] Running user_updates_2020_04_02
[2021-10-15T07:08:41Z INFO  lemmy_server::code_migrations] 0 person rows updated.
[2021-10-15T07:08:41Z INFO  lemmy_server::code_migrations] Running community_updates_2020_04_02
[2021-10-15T07:08:41Z INFO  lemmy_server::code_migrations] 0 community rows updated.
[2021-10-15T07:08:41Z INFO  lemmy_server::code_migrations] Running post_updates_2020_04_03
[2021-10-15T07:08:41Z INFO  lemmy_server::code_migrations] 0 post rows updated.
[2021-10-15T07:08:41Z INFO  lemmy_server::code_migrations] Running comment_updates_2020_04_03
[2021-10-15T07:08:41Z INFO  lemmy_server::code_migrations] 0 comment rows updated.
[2021-10-15T07:08:41Z INFO  lemmy_server::code_migrations] Running private_message_updates_2020_05_05
[2021-10-15T07:08:41Z INFO  lemmy_server::code_migrations] 0 private message rows updated.
[2021-10-15T07:08:41Z INFO  lemmy_server::code_migrations] Running post_thumbnail_url_updates_2020_07_27
[2021-10-15T07:08:41Z INFO  lemmy_server::code_migrations] 0 Post thumbnail_url rows updated.
[2021-10-15T07:08:41Z INFO  lemmy_server::code_migrations] Running apub_columns_2021_02_02
[2021-10-15T07:08:41Z INFO  lemmy_server::scheduled_tasks] Updating active site and community aggregates ...
Starting http server at 0.0.0.0:1235
[2021-10-15T07:08:41Z INFO  lemmy_server::scheduled_tasks] Done.
[2021-10-15T07:08:41Z INFO  lemmy_server::scheduled_tasks] Reindexing table concurrently post_aggregates ...
thread '<unnamed>' panicked at 'reindex table: DatabaseError(__Unknown, "syntax error at or near \"concurrently\"")', src/scheduled_tasks.rs:55:34
stack backtrace:
   0: rust_begin_unwind
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/panicking.rs:92:14
   2: core::result::unwrap_failed
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/result.rs:1599:5
   3: core::result::Result<T,E>::expect
   4: lemmy_server::scheduled_tasks::reindex_table
   5: lemmy_server::scheduled_tasks::reindex_aggregates_tables
   6: lemmy_server::scheduled_tasks::setup
   7: lemmy_server::main::{{closure}}::{{closure}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
Would appreciate any help. Thank you

**Comment by prezmix** [comment]
This may have been due to compiling from the main branch. I switched to 'release/v0.13' and tried again, however this time I get:

```
root@5f16f5299b4e:/data/lemmy# cargo run
    Finished dev [unoptimized] target(s) in 2.63s
     Running `target/debug/lemmy_server`
warning: invalid logging spec 'info"', ignoring it
Error: LemmyError { inner: Failed with: schema "utils" already exists }
```
