### ISSUE TITLE
Error connecting to postgresql

### ISSUE THREAD

**Issue by Slips-PC** [LemmyNet/lemmy#2308]
### Issue Summary

When I start lemmy with `docker-compose up`, I get an error that Lemmy failed to connect to PostgreSQL.
`thread 'main' panicked at 'Error connecting to postgres://lemmy:[passwordhere]@localhost:5432/lemmy', src/main.rs:68:25`

### Steps to Reproduce

1. Follow the guide provided on the site.
2. Set a custom password in both `docker-compose.yaml` and `lemmy.hjson`
3. Start with `docker-compose up`

### Technical details
Logfile: 
```
pictrs_1    | 2022-06-08T18:09:43.463286Z  INFO restructure{store=FileStore { path_gen: "generator", root_dir: "/mnt" }}: pict_rs::store::file_store::restructure: new
pictrs_1    | 2022-06-08T18:09:43.464125Z  INFO restructure{store=FileStore { path_gen: "generator", root_dir: "/mnt" }}: pict_rs::store::file_store::restructure: close time.busy=467µs time.idle=379µs
postgres_1  |
postgres_1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
postgres_1  |
pictrs_1    | 2022-06-08T18:09:43.467774Z  INFO actix_server::builder: Starting 3 workers
postgres_1  | 2022-06-08 18:09:43.527 UTC [1] LOG:  starting PostgreSQL 12.11 on x86_64-pc-linux-musl, compiled by gcc (Alpine 11.2.1_git20220219) 11.2.1 20220219, 64-bit
postgres_1  | 2022-06-08 18:09:43.527 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres_1  | 2022-06-08 18:09:43.527 UTC [1] LOG:  listening on IPv6 address "::", port 5432
pictrs_1    | 2022-06-08T18:09:43.469786Z  INFO actix_server::server: Actix runtime found; starting in Actix runtime
postgres_1  | 2022-06-08 18:09:43.528 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1  | 2022-06-08 18:09:43.539 UTC [21] LOG:  database system was shut down at 2022-06-08 18:09:35 UTC
postgres_1  | 2022-06-08 18:09:43.550 UTC [1] LOG:  database system is ready to accept connections
lemmy-ui_1  | Inferno is in development mode.
lemmy-ui_1  | httpbase: http://localhost:8536
lemmy-ui_1  | wsUri: ws://localhost:8536/api/v3/ws
lemmy-ui_1  | isHttps: false
lemmy-ui_1  | No JWT cookie found.
lemmy-ui_1  | http://0.0.0.0:1234
lemmy-ui_1  | FetchError: request to http://localhost:8536/api/v3/site? failed, reason: connect ECONNREFUSED 127.0.0.1:8536
lemmy-ui_1  |     at ClientRequest.<anonymous> (/app/node_modules/node-fetch/lib/index.js:1483:11)
lemmy-ui_1  |     at ClientRequest.emit (node:events:527:28)
lemmy-ui_1  |     at Socket.socketErrorListener (node:_http_client:454:9)
lemmy-ui_1  |     at Socket.emit (node:events:527:28)
lemmy-ui_1  |     at emitErrorNT (node:internal/streams/destroy:151:8)
lemmy-ui_1  |     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
lemmy-ui_1  |     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
lemmy-ui_1  |   type: 'system',
lemmy-ui_1  |   errno: 'ECONNREFUSED',
lemmy-ui_1  |   code: 'ECONNREFUSED'
lemmy-ui_1  | }
lemmy_1     | thread 'main' panicked at 'Error connecting to postgres://lemmy:passtesthere@localhost:5432/lemmy', src/main.rs:68:25
lemmy_1     | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
* What OS are you trying to install lemmy on: Debian 11

### What I've Tried
* `rm -rf`ing volumes/postgres
* confirming the password is correct
* Checking the backtrace with RUST_BACKTRACE=1 (Nothing showed)

My apologies if this is obvious, I'm not exactly familiar with Rust *or* docker.

**Comment by dessalines** [comment]
This usually happens when you start the containers, then change the passwords after. You must change both of them before.
