### ISSUE TITLE
Failure to Compile 64 bit on Windows 10 -   rustc panicked on compiling db_schema

### ISSUE THREAD

**Issue by GeekVisit** [LemmyNet/lemmy#2534]
Found a bug? Please fill out the sections below. 👍

For front end issues, use [lemmy-ui](https://github.com/LemmyNet/lemmy-ui)

### Issue Summary

panic having following message:
```
  *  Executing task: CodeLLDB: cargo 

Running `cargo build --bin=lemmy_server --package=lemmy_server --message-format=json`...
   Compiling lemmy_db_schema v0.16.5 (c:\Users\gk\Documents\lemmy-lemmy\lemmy\crates\db_schema)
thread 'rustc' panicked at 'assertion failed: pos.get() <= self.position()', compiler\rustc_metadata\src\rmeta\encoder.rs:424:9
stack backtrace:
   0:     0x7ffc2d8d8fb2 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1086ecfa86360858
   1:     0x7ffc2d9140db - core::fmt::write::hbadbc3de7beb6abb
   2:     0x7ffc2d8cb8aa - <std::io::IoSlice as core::fmt::Debug>::fmt::hb7e33fb242ec9ac1
   3:     0x7ffc2d8dc5b4 - std::panicking::default_hook::hb8b3ce065b661264
   4:     0x7ffc2d8dc1ea - std::panicking::default_hook::hb8b3ce065b661264
   5:     0x7ffbf3f725ee - rustc_driver[c6471a3a75cc3305]::describe_lints
   6:     0x7ffc2d8dcfb2 - std::panicking::rust_panic_with_hook::h33e40e3f5d3be1f3
   7:     0x7ffc2d8dccfa - <std::panicking::begin_panic_handler::StrPanicPayload as core::panic::BoxMeUp>::get::h5aceb4e60531e534
   8:     0x7ffc2d8d9cbf - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1086ecfa86360858
   9:     0x7ffc2d8dca00 - rust_begin_unwind
  10:     0x7ffc2d949905 - core::panicking::panic_fmt::h0af4781e6a0c54d3
  11:     0x7ffc2d9497ac - core::panicking::panic::hd1f6d7a0e46f29da
  12:     0x7ffbf3a8425a - <rustc_metadata[fe368d8b15f8597]::rmeta::encoder::EncodeContext as rustc_type_ir[1421f89e31f06786]::codec::TyEncoder>::predicate_shorthands
  13:     0x7ffbf25330b0 - rustc_metadata[fe368d8b15f8597]::rmeta::encoder::encode_metadata
  14:     0x7ffbf2533d6a - <rustc_metadata[fe368d8b15f8597]::rmeta::encoder::EncodeContext as rustc_serialize[5ba6e6ef117c5717]::serialize::Encoder>::emit_raw_bytes
  15:     0x7ffbf253224e - rustc_metadata[fe368d8b15f8597]::rmeta::encoder::encode_metadata
  16:     0x7ffbf253e384 - rustc_metadata[fe368d8b15f8597]::fs::encode_and_write_metadata
  17:     0x7ffbf190f0fb - <rustc_interface[9c167b8dd5fe1201]::passes::LintStoreExpandImpl as rustc_expand[aa25ec99d7328c25]::base::LintStoreExpand>::pre_expansion_lint
  18:     0x7ffbf18fd55c - <rustc_interface[9c167b8dd5fe1201]::queries::Queries>::ongoing_codegen
  19:     0x7ffbf18ba3d9 - rustc_driver[c6471a3a75cc3305]::main
  20:     0x7ffbf18ee32a - <rustc_middle[12c473a188441910]::ty::SymbolName as core[8087a2e8d825f5e1]::fmt::Debug>::fmt
  21:     0x7ffbf18d5e60 - rustc_driver[c6471a3a75cc3305]::main
  22:     0x7ffbf18ed7d7 - <rustc_middle[12c473a188441910]::ty::SymbolName as core[8087a2e8d825f5e1]::fmt::Debug>::fmt
  23:     0x7ffbf18de109 - rustc_driver[c6471a3a75cc3305]::main
  24:     0x7ffbf18de56d - rustc_driver[c6471a3a75cc3305]::main
  25:     0x7ffc2d8ed7cc - std::sys::windows::thread::Thread::new::h742bb0c6405f02e2
  26:     0x7ffc6c6c7034 - BaseThreadInitThunk
  27:     0x7ffc6d782651 - RtlUserThreadStart

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.65.0 (897e37553 2022-11-02) running on x86_64-pc-windows-msvc

note: compiler flags: --crate-type lib -C embed-bitcode=no -C debuginfo=0 -C incremental=[REDACTED] -C strip=symbols

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `lemmy_db_schema`
Error: Cargo invocation failed.
    at t.Cargo.getCargoArtifacts (c:\Users\gk\.vscode\extensions\vadimcn.vscode-lldb-1.8.1\extension.js:1:11568)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.open (c:\Users\gk\.vscode\extensions\vadimcn.vscode-lldb-1.8.1\extension.js:1:9878)
Caused by: Error: exit code: 101.
    at ChildProcess.<anonymous> (c:\Users\gk\.vscode\extensions\vadimcn.vscode-lldb-1.8.1\extension.js:1:13171)
    at ChildProcess.emit (node:events:526:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
 *  The terminal process terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it. 

```

### Steps to Reproduce

1. Git clone lemmy and update submodules
2. in VSCode run debug it runs `cargo build --bin=lemmy_server --package=lemmy_server --message-format=json`
3. I get the above error.

**Comment by Nutomic** [comment]
> note: the compiler unexpectedly panicked. this is a bug.
> 
> note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

**Comment by dessalines** [comment]
What is that strange command? Please use the docker development instructions, we can't possibly debug every possible system setup.
