### ISSUE TITLE
[Bug]: Building `console` feature requires `tokio_unstable` rustflag, panics otherwise

### ISSUE THREAD

**Issue by wereii** [LemmyNet/lemmy#4553]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

Building lemmy with `console` (for OTLP tracing) feature **and** setting `opentelemetry_url` will result in:

```rs
lemmy-1  | thread 'main' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/console-subscriber-0.1.10/src/lib.rs:266:9:
lemmy-1  | task tracing requires Tokio to be built with RUSTFLAGS="--cfg tokio_unstable"!
lemmy-1  | stack backtrace:
lemmy-1  |    0:     0x55f870fbe28c - std::backtrace_rs::backtrace::libunwind::trace::ha637c64ce894333a
lemmy-1  |                                at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
lemmy-1  |    1:     0x55f870fbe28c - std::backtrace_rs::backtrace::trace_unsynchronized::h47f62dea28e0c88d
lemmy-1  |                                at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
lemmy-1  |    2:     0x55f870fbe28c - std::sys_common::backtrace::_print_fmt::h9eef0abe20ede486
lemmy-1  |                                at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:67:5
lemmy-1  |    3:     0x55f870fbe28c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hed7f999df88cc644
lemmy-1  |                                at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:44:22
lemmy-1  |    4:     0x55f870febab0 - core::fmt::rt::Argument::fmt::h1539a9308b8d058d
lemmy-1  |                                at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/fmt/rt.rs:142:9
lemmy-1  |    5:     0x55f870febab0 - core::fmt::write::h3a39390d8560d9c9
lemmy-1  |                                at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/fmt/mod.rs:1120:17
lemmy-1  |    6:     0x55f870fbb23f - std::io::Write::write_fmt::h5fc9997dfe05f882
lemmy-1  |                                at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/io/mod.rs:1762:15
lemmy-1  |    7:     0x55f870fbe074 - std::sys_common::backtrace::_print::h894006fb5c6f3d45
lemmy-1  |                                at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:47:5
lemmy-1  |    8:     0x55f870fbe074 - std::sys_common::backtrace::print::h23a2d212c6fff936
lemmy-1  |                                at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:34:9
lemmy-1  |    9:     0x55f870fbf827 - std::panicking::default_hook::{{closure}}::h8a1d2ee00185001a
lemmy-1  |   10:     0x55f870fbf58f - std::panicking::default_hook::h6038f2eba384e475
lemmy-1  |                                at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:292:9
lemmy-1  |   11:     0x55f870fbfca8 - std::panicking::rust_panic_with_hook::h2b5517d590cab22e
lemmy-1  |                                at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:779:13
lemmy-1  |   12:     0x55f870fbfb59 - std::panicking::begin_panic_handler::{{closure}}::h233112c06e0ef43e
lemmy-1  |                                at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:649:13
lemmy-1  |   13:     0x55f870fbe756 - std::sys_common::backtrace::__rust_end_short_backtrace::h6e893f24d7ebbff8
lemmy-1  |                                at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:170:18
lemmy-1  |   14:     0x55f870fbf8f2 - rust_begin_unwind
lemmy-1  |                                at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:645:5
lemmy-1  |   15:     0x55f86ce6b345 - core::panicking::panic_fmt::hbf0e066aabfa482c
lemmy-1  |                                at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:72:14
lemmy-1  |   16:     0x55f86e428cdd - console_subscriber::ConsoleLayer::build::hbf5e99a4902fa020
lemmy-1  |   17:     0x55f86e42815d - console_subscriber::builder::Builder::build::hcd27a9bbf98922c3
lemmy-1  |   18:     0x55f86d730066 - console_subscriber::builder::Builder::spawn::hffaeab610088f890
lemmy-1  |   19:     0x55f86db366b6 - lemmy_server::telemetry::init_tracing::h7f66b8fe44070cc5
lemmy-1  |   20:     0x55f86d03e22e - lemmy_server::init_logging::h89b313ec1d4decfa
lemmy-1  |   21:     0x55f86cfdf225 - lemmy_server::main::{{closure}}::h050fb902f15216bd
lemmy-1  |   22:     0x55f86ce94769 - tokio::runtime::park::CachedParkThread::block_on::{{closure}}::hbe04b2192e4c87cf
lemmy-1  |   23:     0x55f86ce9450a - tokio::runtime::park::CachedParkThread::block_on::ha724e3528ef0f9c9
lemmy-1  |   24:     0x55f86cf9ec2a - tokio::runtime::context::blocking::BlockingRegionGuard::block_on::hc0e7e47a8354da7f
lemmy-1  |   25:     0x55f86ce9b469 - tokio::runtime::scheduler::multi_thread::MultiThread::block_on::{{closure}}::h888423e9d16d6ed1
lemmy-1  |   26:     0x55f86ce92a18 - tokio::runtime::context::runtime::enter_runtime::hf277be7b9aa7e92a
lemmy-1  |   27:     0x55f86ce9b418 - tokio::runtime::scheduler::multi_thread::MultiThread::block_on::h9b7056c713fef0f0
lemmy-1  |   28:     0x55f86cfd1b6e - tokio::runtime::runtime::Runtime::block_on::h3772f34ebe4de6dd
lemmy-1  |   29:     0x55f86d03b47f - lemmy_server::main::h7b655697f52a6c2d
lemmy-1  |   30:     0x55f86cef0e0e - core::ops::function::FnOnce::call_once::h616876ba980eaca2
lemmy-1  |   31:     0x55f86ce93c8d - std::sys_common::backtrace::__rust_begin_short_backtrace::h9fba4e83bb0444a9
lemmy-1  |   32:     0x55f86ce7b171 - std::rt::lang_start::{{closure}}::hd4821cd6e39e607f
lemmy-1  |   33:     0x55f870fb3a67 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hd95060ecd5e1ca24
lemmy-1  |                                at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/ops/function.rs:284:13
lemmy-1  |   34:     0x55f870fb3a67 - std::panicking::try::do_call::h6e8cf51db32a6e4b
lemmy-1  |                                at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:552:40
lemmy-1  |   35:     0x55f870fb3a67 - std::panicking::try::h3a52eefe24fe3c29
lemmy-1  |                                at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:516:19
lemmy-1  |   36:     0x55f870fb3a67 - std::panic::catch_unwind::h24c28c23c02c3841
lemmy-1  |                                at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panic.rs:142:14
lemmy-1  |   37:     0x55f870fb3a67 - std::rt::lang_start_internal::{{closure}}::h705d3c9cbc06ef47
lemmy-1  |                                at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/rt.rs:148:48
lemmy-1  |   38:     0x55f870fb3a67 - std::panicking::try::do_call::ha21f52ba13158470
lemmy-1  |                                at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:552:40
lemmy-1  |   39:     0x55f870fb3a67 - std::panicking::try::h5581346bf6aeb1f8
lemmy-1  |                                at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:516:19
lemmy-1  |   40:     0x55f870fb3a67 - std::panic::catch_unwind::h7919645a6b72e25b
lemmy-1  |                                at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panic.rs:142:14
lemmy-1  |   41:     0x55f870fb3a67 - std::rt::lang_start_internal::h12de51168669836e
lemmy-1  |                                at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/rt.rs:148:20
lemmy-1  |   42:     0x55f86ce7b147 - std::rt::lang_start::h0bfadb7a681c4b89
lemmy-1  |   43:     0x55f86d03b525 - main
lemmy-1  |   44:     0x7f543940124a - <unknown>
lemmy-1  |   45:     0x7f5439401305 - __libc_start_main
lemmy-1  |   46:     0x55f86ce6bc71 - _start
lemmy-1  |   47:                0x0 - <unknown>
```

### Steps to Reproduce

1. Checkout to 0.19.3 tag 
2. `docker build . -f docker/Dockerfile --no-cache --build-arg CARGO_BUILD_FEATURES=default,console --build-arg RUST_RELEASE_MODE=release  -t "lemmy:0.19.3-otlp"`
3. Add `opentelemetry_url: "http://example"` into lemmy.hjson
4. Starting the container will immediately throw the respective error.

### Technical Details

Debian 11.9; kernel 5.10.0-27-amd64
Docker: 25.0.3
Docker Buildx: v0.13.0
Docker Compose:  v2.24.6

### Version

0.19.3

**Comment by wereii** [comment]
You might already be aware of this but I couldn't find any note or discussion, so this is here at least for posterity's sake

**Comment by Nutomic** [comment]
Right you need to set the mentioned env var, Im adding a comment. [Here the documentation](https://docs.rs/tokio/latest/tokio/#unstable-features).

**Comment by wereii** [comment]
Yeah, I also added `RUSTFLAGS=` (empty by default) into the Dockerfile so that this can propagated from build-args, I could PR that if you want.

**Comment by Nutomic** [comment]
Yes sure.

**Comment by asonix** [comment]
fwiw putting the `opentelemetry` stuff behind the `console` feature doesn't make a lot of sense. Even though they both rely on tracing, they are different things and serve different purposes

**Comment by wereii** [comment]
have been digging into this whole thing for last few hours and there seem to be two other problems (I might be blind though):

Minor thing: when enabling OTLP tracing, you have to set RUST_LOG to more verbose values as it also filters out what is sent to the trace consumer (jaeger), this in turn makes console output too verbose with stuff (that I am already getting elsewhere). Adding some kind of `opentelemetry_log` field into the config to control this separately would be nice.
[The code in question.](https://github.com/LemmyNet/lemmy/blob/2fd81067c7130a23cabfff8bfa76b349b87e8426/src/telemetry.rs#L44)

Bigger thing: HTTP Tracing across services does not work.
The incoming trace_id is ignored (proxy sets `uber-trace-id` header, https://docs.rs/tracing-actix-web/latest/tracing_actix_web/#trace-id, not yet sure how to apply this in root_span_builder, I might be missing something). 
Requests to pict-rs should also pass the trace id, haven't checked it yet but jaeger does not show connections between lemmy and pict-rs so it's probably also not configured in reqwest(-tracing) (?)
