### ISSUE TITLE
Cargo test fail

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [LemmyNet/lemmy#642]
OS: Arch Linux
Lemmy: 0.6.50
Postgresql: 12.2

Output of cargo test
```sql   Compiling lemmy_server v0.0.1 (/home/doc/Code/lemmy/server)
    Finished test [unoptimized + debuginfo] target(s) in 11.21s
     Running target/debug/deps/lemmy_server-6b06dc3023092553

running 18 tests
test apub::tests::test_post ... ok
test apub::tests::test_person ... ok
test apub::tests::test_community ... ok
test db::tests::test_fuzzy_search ... ok
test tests::test_email ... ok
test tests::test_extract_usernames ... ok
test db::category::tests::test_crud ... ok
test db::comment_view::tests::test_crud ... FAILED
test db::moderator::tests::test_crud ... FAILED
test db::post_view::tests::test_crud ... FAILED
test db::password_reset_request::tests::test_crud ... FAILED
test db::user_mention::tests::test_crud ... FAILED
test db::user::tests::test_crud ... FAILED
test db::post::tests::test_crud ... FAILED
test tests::test_slur_filter ... ok
test db::community::tests::test_crud ... FAILED
test db::private_message::tests::test_crud ... FAILED
test db::comment::tests::test_crud ... ok

failures:

---- db::comment_view::tests::test_crud stdout ----
thread 'db::comment_view::tests::test_crud' panicked at 'called `Result::unwrap()` on an `Err` value: DatabaseError(UniqueViolation, "duplicate key value violates unique constraint \"user__name_fedi_name_key\"")', src/db/comment_view.rs:455:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- db::moderator::tests::test_crud stdout ----
thread 'db::moderator::tests::test_crud' panicked at 'called `Result::unwrap()` on an `Err` value: DatabaseError(UniqueViolation, "duplicate key value violates unique constraint \"user__name_fedi_name_key\"")', src/db/moderator.rs:459:24

---- db::post_view::tests::test_crud stdout ----
thread 'db::post_view::tests::test_crud' panicked at 'called `Result::unwrap()` on an `Err` value: DatabaseError(UniqueViolation, "duplicate key value violates unique constraint \"user__name_fedi_name_key\"")', src/db/post_view.rs:380:25

---- db::password_reset_request::tests::test_crud stdout ----
thread 'db::password_reset_request::tests::test_crud' panicked at 'called `Result::unwrap()` on an `Err` value: DatabaseError(UniqueViolation, "duplicate key value violates unique constraint \"user__name_fedi_name_key\"")', src/db/password_reset_request.rs:109:25

---- db::user_mention::tests::test_crud stdout ----
thread 'db::user_mention::tests::test_crud' panicked at 'called `Result::unwrap()` on an `Err` value: DatabaseError(UniqueViolation, "duplicate key value violates unique constraint \"user__name_fedi_name_key\"")', src/db/user_mention.rs:85:25

---- db::user::tests::test_crud stdout ----
thread 'db::user::tests::test_crud' panicked at 'called `Result::unwrap()` on an `Err` value: DatabaseError(UniqueViolation, "duplicate key value violates unique constraint \"user__name_fedi_name_key\"")', src/db/user.rs:207:25

---- db::post::tests::test_crud stdout ----
thread 'db::post::tests::test_crud' panicked at 'called `Result::unwrap()` on an `Err` value: DatabaseError(UniqueViolation, "duplicate key value violates unique constraint \"user__name_fedi_name_key\"")', src/db/post.rs:212:25

---- db::community::tests::test_crud stdout ----
thread 'db::community::tests::test_crud' panicked at 'called `Result::unwrap()` on an `Err` value: DatabaseError(__Unknown, "deadlock detected")', src/db/community.rs:237:25

---- db::private_message::tests::test_crud stdout ----
thread 'db::private_message::tests::test_crud' panicked at 'called `Result::unwrap()` on an `Err` value: DatabaseError(__Unknown, "deadlock detected")', src/db/private_message.rs:86:28


failures:
    db::comment_view::tests::test_crud
    db::community::tests::test_crud
    db::moderator::tests::test_crud
    db::password_reset_request::tests::test_crud
    db::post::tests::test_crud
    db::post_view::tests::test_crud
    db::private_message::tests::test_crud
    db::user::tests::test_crud
    db::user_mention::tests::test_crud

test result: FAILED. 9 passed; 9 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--lib'
```

I was initially very concerned since they were all database related but the server actually runs normal.

**Comment by dessalines** [comment]
The tests should be run with `RUST_TEST_THREADS=1 cargo test` otherwise cargo will try to run them in parallel, and it has some db locking issues. This is in the `.travis.yml`, so that's why all the travis tests are currently passing.

**Comment by Th3Whit3Wolf** [comment]
I get the same same error running `RUST_TEST_THREADS=1 cargo test` and `cargo test -- --test-threads=1`, is this possibly a database issue? I see travis is using postgesql 9.4 and I am on 12.2

**Comment by Th3Whit3Wolf** [comment]
After dropping the database & user and recreating them, running `diesel migration run`, and rerunning the test it seems to work.
