### ISSUE TITLE
Database tests are failing with "deadlock detected"

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#841]
This is on latest master (96f133750dd295d62672beec38232f81764cade8), with a clean database. I ran `DROP SCHEMA public CASCADE; CREATE SCHEMA public;` to remove all the data, and then `cargo run` to create the tables.

However, most of the database tests fail:
```
> cargo test
Finished test [unoptimized + debuginfo] target(s) in 0.12s
Running target/debug/deps/lemmy_server-03d21a032e394f0b

running 21 tests
test apub::tests::test_post ... ok
test apub::tests::test_person ... ok
test apub::tests::test_community ... ok
test db::tests::test_fuzzy_search ... ok
test tests::test_email ... ok
test tests::test_extract_usernames ... ok
test db::category::tests::test_crud ... ok
test db::user::tests::test_crud ... FAILED
test db::user_mention::tests::test_crud ... FAILED
test db::comment::tests::test_crud ... FAILED
test tests::test_valid_community_name ... ok
test db::community::tests::test_crud ... FAILED
test tests::test_valid_register_username ... ok
test tests::test_slur_filter ... ok
test tests::test_image ... ok
test db::post_view::tests::test_crud ... FAILED
test db::private_message::tests::test_crud ... FAILED
test db::password_reset_request::tests::test_crud ... FAILED
test db::moderator::tests::test_crud ... FAILED
test db::post::tests::test_crud ... FAILED
test db::comment_view::tests::test_crud ... ok

failures:

---- db::user::tests::test_crud stdout ----
thread 'db::user::tests::test_crud' panicked at 'called `Result::unwrap()` on an `Err` value: DatabaseError(UniqueViolation, "duplicate key value violates unique constraint \"user__name_fedi_name_key\"")', src/db/user.rs:207:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- db::user_mention::tests::test_crud stdout ----
thread 'db::user_mention::tests::test_crud' panicked at 'called `Result::unwrap()` on an `Err` value: DatabaseError(UniqueViolation, "duplicate key valueviolates unique constraint \"user__name_fedi_name_key\"")', src/db/user_mention.rs:85:25

---- db::comment::tests::test_crud stdout ----
thread 'db::comment::tests::test_crud' panicked at 'called `Result::unwrap()` on an `Err` value: DatabaseError(UniqueViolation, "duplicate key value violates unique constraint \"user__name_fedi_name_key\"")', src/db/comment.rs:191:25

---- db::community::tests::test_crud stdout ----
thread 'db::community::tests::test_crud' panicked at 'called `Result::unwrap()` on an `Err` value: DatabaseError(UniqueViolation, "duplicate key value violates unique constraint \"user__name_fedi_name_key\"")', src/db/community.rs:237:25

---- db::post_view::tests::test_crud stdout ----
thread 'db::post_view::tests::test_crud' panicked at 'called `Result::unwrap()` on an `Err` value: DatabaseError(__Unknown, "deadlock detected")', src/db/post_view.rs:380:25

---- db::private_message::tests::test_crud stdout ----
thread 'db::private_message::tests::test_crud' panicked at 'called `Result::unwrap()` on an `Err` value: DatabaseError(__Unknown, "deadlock detected")', src/db/private_message.rs:86:28

---- db::password_reset_request::tests::test_crud stdout ----
thread 'db::password_reset_request::tests::test_crud' panicked at 'called `Result::unwrap()` on an `Err` value: DatabaseError(__Unknown, "deadlock detected")', src/db/password_reset_request.rs:109:25

---- db::moderator::tests::test_crud stdout ----
thread 'db::moderator::tests::test_crud' panicked at 'called `Result::unwrap()` on an `Err` value: DatabaseError(__Unknown, "deadlock detected")', src/db/moderator.rs:481:25

---- db::post::tests::test_crud stdout ----
thread 'db::post::tests::test_crud' panicked at 'called `Result::unwrap()` on an `Err` value: DatabaseError(__Unknown, "deadlock detected")', src/db/post.rs:226:30


failures:
db::comment::tests::test_crud
db::community::tests::test_crud
db::moderator::tests::test_crud
db::password_reset_request::tests::test_crud
db::post::tests::test_crud
db::post_view::tests::test_crud
db::private_message::tests::test_crud
db::user::tests::test_crud
db::user_mention::tests::test_crud

test result: FAILED. 12 passed; 9 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--lib'
```

Here's one of the backtraces:
```
stack backtrace:
0: backtrace::backtrace::libunwind::trace
at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
1: backtrace::backtrace::trace_unsynchronized
at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
2: std::sys_common::backtrace::_print_fmt
at src/libstd/sys_common/backtrace.rs:78
3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
at src/libstd/sys_common/backtrace.rs:59
4: core::fmt::write
at src/libcore/fmt/mod.rs:1076
5: std::io::Write::write_fmt
at /rustc/56daaf669ebc3d5083db5cded719f780dc31104e/src/libstd/io/mod.rs:1537
6: std::io::impls::<impl std::io::Write for alloc::boxed::Box<W>>::write_fmt
at src/libstd/io/impls.rs:176
7: std::sys_common::backtrace::_print
at src/libstd/sys_common/backtrace.rs:62
8: std::sys_common::backtrace::print
at src/libstd/sys_common/backtrace.rs:49
9: std::panicking::default_hook::{{closure}}
at src/libstd/panicking.rs:198
10: std::panicking::default_hook
at src/libstd/panicking.rs:215
11: std::panicking::rust_panic_with_hook
at src/libstd/panicking.rs:486
12: rust_begin_unwind
at src/libstd/panicking.rs:388
13: core::panicking::panic_fmt
at src/libcore/panicking.rs:101
14: core::option::expect_none_failed
at src/libcore/option.rs:1272
15: core::result::Result<T,E>::unwrap
at /home/felix/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/result.rs:1005
16: lemmy_server::db::comment_view::tests::test_crud
at src/db/comment_view.rs:469
17: lemmy_server::db::comment_view::tests::test_crud::{{closure}}
at src/db/comment_view.rs:432
18: core::ops::function::FnOnce::call_once
at /home/felix/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/ops/function.rs:232
19: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
at /rustc/56daaf669ebc3d5083db5cded719f780dc31104e/src/liballoc/boxed.rs:1076
20: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
at /rustc/56daaf669ebc3d5083db5cded719f780dc31104e/src/libstd/panic.rs:318
21: std::panicking::try::do_call
at /rustc/56daaf669ebc3d5083db5cded719f780dc31104e/src/libstd/panicking.rs:297
22: std::panicking::try
at /rustc/56daaf669ebc3d5083db5cded719f780dc31104e/src/libstd/panicking.rs:274
23: std::panic::catch_unwind
at /rustc/56daaf669ebc3d5083db5cded719f780dc31104e/src/libstd/panic.rs:394
24: test::run_test_in_process
at src/libtest/lib.rs:541
25: test::run_test::run_test_inner::{{closure}}
at src/libtest/lib.rs:450
```

**Comment by dessalines** [comment]
I'm testing these now.

**Comment by dessalines** [comment]
Sorry, I forgot to mention this needs to be run as:

```
psql -U lemmy -c "DROP SCHEMA public CASCADE; CREATE SCHEMA public;"
export DATABASE_URL=postgres://lemmy:password@localhost:5432/lemmy
diesel migration run
RUST_TEST_THREADS=1 cargo test
```

This is correct in the .travis.yml which is why they're passing in our CI.

**Comment by Nutomic** [comment]
Thanks, that works! Need to add it to the docs.
